when:
  - event: [push, manual]

steps:
  - name: build
    image: maven:3.9.9-eclipse-temurin-21-alpine
    commands: |
      export TZ=Europe/Berlin
      mvn clean verify -U --no-transfer-progress -Pproduction
