name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/maven.yaml@master
    with:
      additional-maven-parameters: -Pproduction
      pattern-to-release: optigem-spoonfeeder-*.jar
    secrets: inherit
